Use the new overload of tflite::Verify in the TF Lite Tasks Library, since the other version of tflite::Verify was deprecated in CL 365251064. This new overload doesn't get passed an OpResolver parameter and doesn't check that the operators in the model are supported by the OpResolver.
Doing this, while still ensuring we continue to get reasonable error messages when
processing a model containing ops not supported by the OpResolver, required also extending the ErrorReporter class to keep track of the previous *two* error messages, rather than just the last one, in order to be able to special-case the
situation where AllocateTensors() fails after reporting the two errors, in particular
  ERROR: Encountered unresolved custom op: MY_CUSTOM_OP.
  ERROR: Node number 1 (MY_CUSTOM_OP) failed to prepare.
or
  ERROR: Didn't find op for builtin opcode 'RESHAPE' version '1'. An older version of this builtin might be supported. Are you using an old TFLite binary with a newer model?
  ERROR: Registration failed.

PiperOrigin-RevId: 365949933