Fix a set-but-unused warning in PopulateVector<std::string>.
Chrome encounters this downstream:
error: variable 'v' set but not used [-Werror,-Wunused-but-set-variable]

A more modern way to silence this warning would be to use the C++17
[[maybe_unused]] attribute, but tflite support aims to be at least
C++14 compatible.

PiperOrigin-RevId: 564458227